### ISSUE TITLE
Suggestion: linking Scratch accounts

### ISSUE THREAD

**Issue by ghost** [InternationalScratchWiki/mediawiki-scratch-login#18]
Although this might be difficult to implement per later paragraphs, I think there should be a way for alternate accounts or new accounts on Scratch to log into the main/former account's Wiki account.

I think if this were to be implemented, linking would be done with a special page (I suggest the name could be Special:LinkScratchAccount) and only high-ranking users (in the Scratch Wiki's case, bureaucrats only might be feasible) can link them to avoid faking of alt accounts

For the Scratch Wiki, the Admin Requests page on the Community Portal can be used to request linking of alt accounts, and someone needs to verify they are the same person.

The most major downside I can think of is that non-alts that were accidentally added can log into a Wiki Account, making the wiki more vulnerable to hacking and vandalism. Additionally, there might need to be qualifications over when a Scratch account is allowed to be linked to its main.

**Comment by Kenny2github** [comment]
Verifying that someone is an alt is as simple as getting each account to confirm that they are an alt of the other.
However, it has been Wiki policy for a decade that no alternate accounts are permitted. This is not a feature that we can support.
