### ISSUE TITLE
do not reset code from get requests

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/mediawiki-scratch-login#6]
forms exist for a reason!

**Comment by Kenny2github** [comment]
If it's not a security issue, it's not being fixed in any timeframe.

**Comment by Naleksuh** [comment]
Performing actions via get requests actually is a security issue, and possibly one of the largest ones that can exist (granted, all that can be done is resetting the token unwantedly, but still bad practice).

**Comment by Kenny2github** [comment]
I'm aware it's bad practice, but I've considered all that can go wrong and nothing presents itself as a fully-fledged hole. It's not broken, so it's not worth the effort to fix, at least for now.
